### ISSUE TITLE
schematic pdf hoặc png

### ISSUE THREAD

**Issue by NgoHungCuong** [devanlai/dap42#10]
Bạn có thể cho mình xin schematic dạng pdf hoặc png của bản dùng stm32f042f6p6. Cảm ơn bạn nhiều.

**Comment by devanlai** [comment]
Hi, the hardware schematic can be found in the dap42-hardware repo:
https://github.com/devanlai/dap42-hardware/blob/master/DAP42v2.pdf

**Comment by NgoHungCuong** [comment]
Cảm ơn bạn nhiều nhé.
