### ISSUE TITLE
Add programming instructions to README

### ISSUE THREAD

**Issue by ducky64** [devanlai/dap42#2]
Just to make it very convenient when flashing.

Command to flash ST-Link v2 clones using a CMSIS-DAP adaptor using OpenOCD:

```
openocd -f interface/cmsis-dap.cfg -f target/stm32f1x.cfg \
-c init \
-c "reset halt" \
-c "stm32f1x unlock 0" \
-c reset halt" \
-c "flash erase_sector 0 0 last" \
-c "flash write_bank 0 dap103.bin 0" \
-c "flash verify_bank 0 dap103.bin 0" \
-c "reset run" -c "exit"
```

Might as well link the pinout too:
http://embdev.net/wikifiles_en/thumb/0/09/Stlink-clone-pinout.JPG/800px-Stlink-clone-pinout.JPG
Or, if viewed from the top (LED and MCU side) of the board,

```
(USB header)    SWDIO  GND  SWCLK  3v3    (10-pin programming header)
```

**Comment by devanlai** [comment]
Resolved by commit 01b9738, adding this command as an example

```
openocd -f interface/cmsis-dap.cfg -f target/stm32f1x.cfg \
    -c "init; reset halt" \
    -c "stm32f1x unlock 0; reset halt" \
    -c "flash erase_sector 0 0 last" \
    -c "program DAP103-dapboot-combined-stlink.bin verify reset exit 0x08000000"
```

I decided not to include the pinout information, as there are at least a couple of variants with incompatible SWD pinouts - summarizing the differences is probably a bit too broad of a scope for the README.
