### ISSUE TITLE
Build error ... 

### ISSUE THREAD

**Issue by RandoSY** [devanlai/dap42#5]
Hello,

What  a great project! 

Attempting to build Win10/Ubuntu 17.10 I get ...

C:\Users\randa\Desktop\CMSIS-Dap\dap42-master>make
  BUILD DAP42.bin
USB/cdc.c: In function 'cdc_set_config':
USB/cdc.c:224:60: warning: passing argument 2 of 'cmp_usb_register_control_class_callback' from incompatible pointer type
     cmp_usb_register_control_class_callback(INTF_CDC_DATA, cdc_control_class_request);
                                                            ^
In file included from USB/cdc.c:25:0:
USB/composite_usb_conf.h:102:13: note: expected 'usbd_control_callback' but argument is of type 'int (*)(struct usbd_device *, struct usb_setup_data *, uint8_t **, uint16_t *, void (**)(struct usbd_device *, struct usb_setup_data *))'
 extern void cmp_usb_register_control_class_callback(uint16_t interface,
             ^
USB/cdc.c:225:60: warning: passing argument 2 of 'cmp_usb_register_control_class_callback' from incompatible pointer type
     cmp_usb_register_control_class_callback(INTF_CDC_COMM, cdc_control_class_request);
                                                            ^
In file included from USB/cdc.c:25:0:
USB/composite_usb_conf.h:102:13: note: expected 'usbd_control_callback' but argument is of type 'int (*)(struct usbd_device *, struct usb_setup_data *, uint8_t **, uint16_t *, void (**)(struct usbd_device *, struct usb_setup_data *))'
 extern void cmp_usb_register_control_class_callback(uint16_t interface,
             ^
USB/composite_usb_conf.c: In function 'cmp_usb_set_config':
USB/composite_usb_conf.c:525:9: warning: passing argument 4 of 'usbd_register_control_callback' from incompatible pointer type
         cmp_usb_dispatch_control_class_request);
         ^
In file included from USB/usb_common.h:25:0,
                 from USB/composite_usb_conf.h:22,
                 from USB/composite_usb_conf.c:27:
../libopencm3/include/libopencm3/usb/usbd.h:136:12: note: expected 'usbd_control_callback' but argument is of type 'int (*)(struct usbd_device *, struct usb_setup_data *, uint8_t **, uint16_t *, void (**)(struct usbd_device *, struct usb_setup_data *))'
 extern int usbd_register_control_callback(usbd_device *usbd_dev, uint8_t type,
            ^
USB/dfu.c: In function 'dfu_set_config':
USB/dfu.c:89:55: warning: passing argument 2 of 'cmp_usb_register_control_class_callback' from incompatible pointer type
     cmp_usb_register_control_class_callback(INTF_DFU, dfu_control_class_request);
                                                       ^
In file included from USB/dfu.c:24:0:
USB/composite_usb_conf.h:102:13: note: expected 'usbd_control_callback' but argument is of type 'int (*)(struct usbd_device *, struct usb_setup_data *, uint8_t **, uint16_t *, void (**)(struct usbd_device *, struct usb_setup_data *))'
 extern void cmp_usb_register_control_class_callback(uint16_t interface,
             ^
USB/hid.c: In function 'hid_set_config':
USB/hid.c:177:9: warning: passing argument 4 of 'usbd_register_control_callback' from incompatible pointer type
         hid_control_standard_request);
         ^
In file included from USB/hid.c:21:0:
../libopencm3/include/libopencm3/usb/usbd.h:136:12: note: expected 'usbd_control_callback' but argument is of type 'int (*)(struct usbd_device *, struct usb_setup_data *, uint8_t **, uint16_t *, void (**)(struct usbd_device *, struct usb_setup_data *))'
 extern int usbd_register_control_callback(usbd_device *usbd_dev, uint8_t type,
            ^
USB/hid.c:179:55: warning: passing argument 2 of 'cmp_usb_register_control_class_callback' from incompatible pointer type
     cmp_usb_register_control_class_callback(INTF_HID, hid_control_class_request);
                                                       ^
In file included from USB/hid.c:24:0:
USB/composite_usb_conf.h:102:13: note: expected 'usbd_control_callback' but argument is of type 'int (*)(struct usbd_device *, struct usb_setup_data *, uint8_t **, uint16_t *, void (**)(struct usbd_device *, struct usb_setup_data *))'
 extern void cmp_usb_register_control_class_callback(uint16_t interface,
             ^
CAN/can.c: In function 'can_reconfigure':
CAN/can.c:143:9: error: too many arguments to function 'can_filter_id_mask_32bit_init'
         can_filter_id_mask_32bit_init(CAN1,
         ^
In file included from CAN/can.c:19:0:
../libopencm3/include/libopencm3/stm32/can.h:658:6: note: declared here
 void can_filter_id_mask_32bit_init(uint32_t nr, uint32_t id,
      ^
make[1]: *** [CAN/can.o] Error 1
make: *** [DAP42.bin] Error 2

I built against the latest openlibcm3...

Best,

Randy

**Comment by devanlai** [comment]
Hi @RandoSY,
I normally build against a specific commit hash of libopencm3, which is setup as a submodule. The libopencm3 API is not guaranteed to be stable, so using the latest version may not work. I've pushed a commit to update to the latest version of libopencm3 on this branch:
https://github.com/devanlai/dap42/tree/locm3-update

I need to dig up my boards so that I can do regression testing before I merge this into an official release, but feel free to try it out if you're not able to use the libopencm3 version that dap42 currently uses.

**Comment by devanlai** [comment]
Sorry it's been a while, but I updated to the latest version of libopencm3 - if you feel like compiling against the latest version of libopencm3 instead of the submoduled copy, it should be compatible for the time being.
